services:
  web:
    build: .
    depends_on:
    - db
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
    - ./output_graphs:/app/output_graphs

  
  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  #tests:
  #  build: .
  #  command: pytest
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - db

#  locust:
#    image: locustio/locust
#    container_name: locust
#    depends_on:
#      - web
#    ports:
#      - "8089:8089"
#    volumes:
#      - ./tests/:/app/tests
#    command: >
#      -f /app/tests/locust.py
#      --host http://fastapi:8000



volumes:
  postgres_data:
